[2021-10-12 17:24:00,006] [41345] [INFO] - record_capture.append_failed (record_capture.py:247) - 开始重推失败数据
[2021-10-12 17:24:00,006] [41345] [INFO] - record_capture.start_capture (record_capture.py:209) - 开始录音数据获取及推送
[2021-10-12 17:24:00,007] [41345] [INFO] - record_capture.get_data_from_file (record_capture.py:69) - 文件不存在：record_file/2021-10-11/failed_records.txt
[2021-10-12 17:25:00,006] [41345] [INFO] - record_capture.append_failed (record_capture.py:247) - 开始重推失败数据
[2021-10-12 17:25:00,006] [41345] [INFO] - record_capture.start_capture (record_capture.py:209) - 开始录音数据获取及推送
[2021-10-12 17:25:00,006] [41345] [INFO] - record_capture.get_data_from_file (record_capture.py:69) - 文件不存在：record_file/2021-10-11/failed_records.txt
[2021-10-12 17:26:00,007] [41345] [INFO] - record_capture.append_failed (record_capture.py:247) - 开始重推失败数据
[2021-10-12 17:26:00,007] [41345] [INFO] - record_capture.start_capture (record_capture.py:209) - 开始录音数据获取及推送
[2021-10-12 17:26:00,007] [41345] [INFO] - record_capture.get_data_from_file (record_capture.py:69) - 文件不存在：record_file/2021-10-11/failed_records.txt
[2021-10-12 17:27:00,007] [41345] [INFO] - record_capture.append_failed (record_capture.py:247) - 开始重推失败数据
[2021-10-12 17:27:00,007] [41345] [INFO] - record_capture.start_capture (record_capture.py:209) - 开始录音数据获取及推送
[2021-10-12 17:27:00,007] [41345] [INFO] - record_capture.get_data_from_file (record_capture.py:69) - 文件不存在：record_file/2021-10-11/failed_records.txt
[2021-10-12 17:28:00,006] [41345] [INFO] - record_capture.append_failed (record_capture.py:247) - 开始重推失败数据
[2021-10-12 17:28:00,006] [41345] [INFO] - record_capture.start_capture (record_capture.py:209) - 开始录音数据获取及推送
[2021-10-12 17:28:00,006] [41345] [INFO] - record_capture.get_data_from_file (record_capture.py:69) - 文件不存在：record_file/2021-10-11/failed_records.txt
[2021-10-12 17:29:00,005] [41345] [INFO] - record_capture.append_failed (record_capture.py:247) - 开始重推失败数据
[2021-10-12 17:29:00,005] [41345] [INFO] - record_capture.start_capture (record_capture.py:209) - 开始录音数据获取及推送
[2021-10-12 17:29:00,006] [41345] [INFO] - record_capture.get_data_from_file (record_capture.py:69) - 文件不存在：record_file/2021-10-11/failed_records.txt
[2021-10-12 17:30:00,004] [41345] [INFO] - record_capture.append_failed (record_capture.py:247) - 开始重推失败数据
[2021-10-12 17:30:00,004] [41345] [INFO] - record_capture.start_capture (record_capture.py:209) - 开始录音数据获取及推送
[2021-10-12 17:30:00,004] [41345] [INFO] - record_capture.get_data_from_file (record_capture.py:69) - 文件不存在：record_file/2021-10-11/failed_records.txt
[2021-10-12 17:31:00,002] [41345] [INFO] - record_capture.append_failed (record_capture.py:247) - 开始重推失败数据
[2021-10-12 17:31:00,002] [41345] [INFO] - record_capture.start_capture (record_capture.py:209) - 开始录音数据获取及推送
[2021-10-12 17:31:00,002] [41345] [INFO] - record_capture.get_data_from_file (record_capture.py:69) - 文件不存在：record_file/2021-10-11/failed_records.txt
[2021-10-12 17:32:00,013] [41345] [INFO] - record_capture.append_failed (record_capture.py:247) - 开始重推失败数据
[2021-10-12 17:32:00,013] [41345] [INFO] - record_capture.get_data_from_file (record_capture.py:69) - 文件不存在：record_file/2021-10-11/failed_records.txt
[2021-10-12 17:32:00,015] [41345] [INFO] - record_capture.start_capture (record_capture.py:209) - 开始录音数据获取及推送
[2021-10-12 17:33:00,008] [41345] [INFO] - record_capture.append_failed (record_capture.py:247) - 开始重推失败数据
[2021-10-12 17:33:00,009] [41345] [INFO] - record_capture.get_data_from_file (record_capture.py:69) - 文件不存在：record_file/2021-10-11/failed_records.txt
[2021-10-12 17:33:00,010] [41345] [INFO] - record_capture.start_capture (record_capture.py:209) - 开始录音数据获取及推送
